#Database PostgreSQL

development:
  database: espinapp_dev
  adapter: postgresql
  host: localhost

test:
  database: espinapp_test
  adapter: postgresql
  host: localhost

stage:
  adapter: postgresql
  database: espinapp_stage
  pool: 5
  timeout: 5000

production:
  database: espinapp_production
  adapter:  postgresql
  host:     127.0.0.1
  username: deploy
  password: ""
  pool:     20
  timeout:  30000
